from rationalbreaks import timers
from time import sleep

if __name__ == "__main__":
    timer = timers.RatioNalTimer()
    timer.start()
    print(timer.status())
    print(f"Worked time: {timer.work_time()}")
    print(f"Resting time: {timer.rest_time()}")
    sleep(3)
    print(timer.status())
    print(f"Worked time: {timer.work_time()}")
    print(f"Resting time: {timer.rest_time()}")
    sleep(10)
    print(timer.status())
    print(f"Worked time: {timer.work_time()}")
    print(f"Resting time: {timer.rest_time()}")
    timer.rest()
    sleep(3)
    print(timer.status())
    print(f"Worked time: {timer.work_time()}")
    print(f"Resting time: {timer.rest_time()}")
    sleep(3)
    print(timer.status())
    print(f"Worked time: {timer.work_time()}")
    print(f"Resting time: {timer.rest_time()}")
    timer.continue_work()
    sleep(3)
    print(timer.status())
    print(f"Worked time: {timer.work_time()}")
    print(f"Resting time: {timer.rest_time()}")
    sleep(3)
    print(timer.status())
    print(f"Worked time: {timer.work_time()}")
    print(f"Resting time: {timer.rest_time()}")
    timer.rest()
    sleep(3)
    print(timer.status())
    print(f"Worked time: {timer.work_time()}")
    print(f"Resting time: {timer.rest_time()}")